name: build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  storage_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TFSTATE_REGION }}
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - shell: bash
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
        run: make storage_list
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.TFSTATE_REGION }}
          TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}
          TFSTATE_REGION: ${{ secrets.TFSTATE_REGION }}
          TF_VAR_bucket: ${{ secrets.TF_VAR_BUCKET }}
          TF_VAR_home_ip: ${{ secrets.TF_VAR_HOME_IP }}
          TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}
        run: make infrastructure
