name: build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${TFSTATE_REGION}
      - uses: aws-actions/amazon-ecr-login@v1
      - name: build and upload image
        run: make scripts
  storage_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${TFSTATE_REGION}
      - uses: aws-actions/amazon-ecr-login@v1
      - name: build and upload image
        run: make storage_list
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: run terraform
        run: make infrastructure
